### ISSUE TITLE
Unresolved variables in automated-account-configuration.template "%%BUCKET_NAME%%

### ISSUE THREAD

**Issue by ErikOAWS** [awslabs/automated-account-configuration#1]
Stack does not create successfully. There are unresolved variables in `automated-account-configuration/deployment/automated-account-configuration.template` which causes the `MyLayer` resource to fail create.

https://github.com/awslabs/automated-account-configuration/blob/7c0ad90a884d123f8c8152994b5b92d4b030d025/deployment/automated-account-configuration.template#L2
https://github.com/awslabs/automated-account-configuration/blob/7c0ad90a884d123f8c8152994b5b92d4b030d025/deployment/automated-account-configuration.template#L19
https://github.com/awslabs/automated-account-configuration/blob/7c0ad90a884d123f8c8152994b5b92d4b030d025/deployment/automated-account-configuration.template#L20

![image](https://user-images.githubusercontent.com/50037376/139609218-536634b6-aed9-43a2-8217-3b448b062f72.png)

![image](https://user-images.githubusercontent.com/50037376/139609479-76007e0e-df8a-4ed5-9ba7-5fe6a682983d.png)

**Comment by nrabban** [comment]
Please follow these steps to deploy the solution:

1- From readme, go to Deployment
2- Click on Implementation guide and follow steps in the automated deployment section: https://docs.aws.amazon.com/solutions/latest/automated-account-configuration/automated-deployment.html#launch-the-automated-account-configuration-stack

This step will launch a pre-built CloudFormation template that deploys the solution. The template in the source code needs to be built before it is ready to be used.  We will create a new release with steps to walk through doing a local build. 

Please let us know if you still have any questions.

**Comment by ErikOAWS** [comment]
I had cloned the repo and was using the templates from there.
Using the specific template links of the same name from [here](https://docs.aws.amazon.com/solutions/latest/automated-account-configuration/automated-deployment.html) worked - thanks!
